# Generated by Django 4.0.3 on 2022-04-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_client_id_user_is_sso_user_sso_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session_id',
            new_name='token',
        ),
    ]
