# Generated by Django 4.0.3 on 2022-04-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_session_id_usersession_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
